openapi: 3.0.3
info:
  title: Codelist Service API
  description: |
    This API provides access to various code lists, also known as dictionaries or enumerations, which are fundamental for the IS/STAG system.
  version: 1.0.0
  contact:
    name: STAG Support
    email: stag@service.zcu.cz
    url: https://is-stag.zcu.cz/zakaznici/Support.html

servers:
  - url: /api/v1
    description: Codelist Service API through API Gateway

tags:
  - name: addresses
    description: Operations for managing addresses
  - name: countries
    description: Operations for managing countries
  - name: domains
    description: Operations for managing codelist domains

paths:

  /addresses:
    get:
      tags:
        - addresses
      summary: Get addresses
      description: Retrieve list of addresses available in the system based on the specified filters.
      operationId: getAddresses
      parameters:
        - $ref: '#/components/parameters/Query'
        - $ref: '#/components/parameters/Limit'
      responses:
        '200':
          description: List of addresses matching the specified filters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddressListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '500':
          $ref: '#/components/responses/500InternalServerError'
        'default':
          $ref: '#/components/responses/Default'

  /countries:
    get:
      tags:
        - countries
      summary: Get all countries
      description: Retrieve list of all countries available in the system.
      operationId: getCountries
      parameters:
        - $ref: '#/components/parameters/AcceptLanguage'
      responses:
        '200':
          description: List of available countries.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '500':
          $ref: '#/components/responses/500InternalServerError'
        'default':
          $ref: '#/components/responses/Default'

  /domains:
    get:
      tags:
        - domains
      summary: Get all domains
      description: Retrieve list of all domains available in the code lists system.
      operationId: getDomains
      responses:
        '200':
          description: List of available domains.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '500':
          $ref: '#/components/responses/500InternalServerError'
        'default':
          $ref: '#/components/responses/Default'

  /domains/{domain}:
    get:
      tags:
        - domains
      summary: Get domain values
      description: Retrieve a domain values by its unique identifier.
      operationId: getDomainValues
      parameters:
        - $ref: '#/components/parameters/AcceptLanguage'
        - $ref: '#/components/parameters/Domain'
      responses:
        '200':
          description: Domain details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainValueListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
        'default':
          $ref: '#/components/responses/Default'

components:

  parameters:

    AcceptLanguage:
      name: Accept-Language
      in: header
      description: Preferred language.
      required: false
      schema:
        type: string
        enum:
          - cs
          - en
        default: cs

    Query:
      name: query
      in: query
      description: Query string.
      required: false
      schema:
        type: string
        maxLength: 300
        example: "Czech"
        default: ""

    Limit:
      name: limit
      in: query
      description: Maximum number of results to return.
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 10
        default: 10
        example: 10

    Domain:
      name: domain
      in: path
      required: true
      description: The unique identifier of the domain to retrieve.
      schema:
        $ref: '#/components/schemas/Domain'

  schemas:

    AddressListResponse:
      type: object
      title: Address List Response
      description: Response containing a list of addresses.
      additionalProperties: false
      nullable: false
      required:
        - addresses
      properties:
        addresses:
          type: array
          description: List of addresses.
          items:
            $ref: '#/components/schemas/Address'
          maxItems: 20
          nullable: false
          uniqueItems: true
          example:
            - id: 1
              name: "Lysá 617, Želechovice nad Dřevnicí, 76311"
            - id: 2
              name: "Nádražní 41, Plzeň, 30100"

    Address:
      type: object
      title: Address
      description: Response containing an address.
      additionalProperties: false
      nullable: false
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int32
          nullable: false
          description: Unique identifier of the address.
          example: 1
          minimum: 1
        name:
          type: string
          nullable: false
          description: Fully formatted address.
          example: "Lysá 617, Želechovice nad Dřevnicí, 76311"
          minLength: 1
          maxLength: 500

    CountryListResponse:
      type: object
      title: Country List Response
      description: Response containing a list of countries.
      additionalProperties: false
      nullable: false
      required:
        - countries
      properties:
        countries:
          type: array
          description: List of countries.
          items:
            $ref: '#/components/schemas/Country'
          minItems: 1
          nullable: false
          uniqueItems: true
          example:
            - id: 203
              name: Czech Republic
              commonName: Czechia
              abbreviation: CZ
            - id: 204
              name: Slovak Republic
              commonName: Slovakia
              abbreviation: SK

    Country:
      type: object
      title: Country
      description: Response containing a country.
      additionalProperties: false
      nullable: false
      required:
        - id
        - name
        - commonName
        - abbreviation
      properties:
        id:
          type: integer
          format: int32
          nullable: false
          description: Unique identifier of the country.
          example: 203
          minimum: 1
        name:
          type: string
          nullable: false
          description: Name of the country.
          example: Czech Republic
          maxLength: 240
        commonName:
          type: string
          nullable: true
          description: Common name of the country.
          example: Czechia
          maxLength: 70
        abbreviation:
          type: string
          nullable: false
          description: Abbreviation of the country.
          example: CZ
          maxLength: 2

    DomainListResponse:
      type: object
      title: Domain List Response
      description: Response containing a list of codelist domains.
      additionalProperties: false
      nullable: false
      required:
        - domains
      properties:
        domains:
          type: array
          description: List of codelist domains.
          items:
            $ref: '#/components/schemas/Domain'
          minItems: 1
          nullable: false
          uniqueItems: true
      example:
        domains:
          - TITUL_PRED
          - TITUL_ZA
          - STAV
          - CIS_BANK
          - FAKULTA

    Domain:
      type: string
      title: Domain
      nullable: false
      description: A domain name.
      example: FAKULTA
      minLength: 1
      maxLength: 100

    DomainValueListResponse:
      type: object
      title: Domain Value List Response
      description: Response containing a list of values belonging to the specified domain.
      additionalProperties: false
      nullable: false
      required:
        - values
      properties:
        values:
          type: array
          description: List of values belonging to the specified domain.
          items:
            $ref: '#/components/schemas/DomainValue'
          minItems: 1
          nullable: false
          uniqueItems: true
          example:
            - key: "FAV"
              name: "Fakulta aplikovaných věd"
              abbreviation: "FAV"
            - key: "FEL"
              name: "Fakulta elektrotechnická"
              abbreviation: "FEL"

    DomainValue:
      type: object
      title: Domain Value
      description: Object representing a value belonging to the specified domain.
      additionalProperties: false
      nullable: false
      required:
        - key
        - name
        - abbreviation
      properties:
        key:
          type: string
          nullable: false
          description: Key of the value.
          example: FAV
          minLength: 1
          maxLength: 240
        name:
          type: string
          nullable: false
          description: Name of the value.
          example: Fakulta aplikovaných věd
          minLength: 1
          maxLength: 240
        abbreviation:
          type: string
          nullable: true
          description: Abbreviation of the value.
          example: FAV
          maxLength: 240

    ProblemDetail:
      type: object
      title: Problem Detail
      description: A generic error.
      additionalProperties: false
      nullable: false
      required:
        - type
        - title
        - status
        - detail
        - instance
      properties:
        type:
          type: string
          format: uri
          nullable: false
          description: A URI reference that identifies the problem type.
          example: "http://localhost:8080/countries"
          pattern: ^((about:blank)|(https?://[^\s]+))$
          maxLength: 1000
        title:
          type: string
          nullable: false
          description: A short, human-readable summary of the problem type.
          example: Internal Server Error
          pattern: ^[A-Za-z0-9\s\-.,!?:;'"]+$
          maxLength: 255
        status:
          type: integer
          format: int32
          nullable: false
          description: The HTTP status code.
          example: 404
        detail:
          type: string
          nullable: false
          description: A human-readable explanation specific to this occurrence of the problem.
          example: An unexpected error occurred
          pattern: ^[A-Za-z0-9\s\-.,!?:;'"]+$
          maxLength: 1000
        instance:
          type: string
          nullable: false
          description: A URI reference that identifies the specific occurrence of the problem.
          example: /countries
          pattern: ^(/[^\s]*)+$
          maxLength: 1000
        contextInfo:
          type: object
          additionalProperties: true
          nullable: false
          maxProperties: 5
          description: A free-form based object that contains additional context about the error.
          example:
            domain: Something went wrong

  responses:

    400BadRequest:
      description: Bad request.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
          example:
            type: http://localhost:8080/api/v1/bad-request
            title: Bad Request
            status: 400
            detail: Invalid Language header
            instance: /api/v1/countries

    401Unauthorized:
      description: Access token is missing or invalid.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
          example:
            type: http://localhost:8080/api/v1/unauthorized
            title: Unauthorized
            status: 401
            detail: Access token is missing or invalid
            instance: /api/v1/countries

    403Forbidden:
      description: You do not have permission to access this resource.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
          example:
            type: http://localhost:8080/api/v1/forbidden
            title: Forbidden
            status: 403
            detail: You do not have permission to access this resource
            instance: /api/v1/countries

    404NotFound:
      description: The specified resource was not found.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
          example:
            type: http://localhost:8080/api/v1/domain-not-found
            title: Domain Not Found
            status: 404
            detail: 'Domain with ID: STAT not found'
            instance: /api/v1/domains/STAT

    500InternalServerError:
      description: Internal server error.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
          example:
            type: http://localhost:8080/api/v1/internal-server-error
            title: Internal server error
            status: 500
            detail: An unexpected error occurred
            instance: /api/v1/countries

    Default:
      description: Unexpected error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'

